### ISSUE TITLE
Req: Support for more players

### ISSUE THREAD

**Issue by bobpaul** [andrsdt/explodingKittensTTS#2]
A single exploding kittens deck (regular or nsfw) supports up to 5 players. Using multiple decks (2x NSFW) allows playing up to 9 players (some people combine NSFW + Regular for this, but then the odds of getting pairs is reduced)

The imploding kittens expansion increases the max player count by +1.

Streaking kittens expansion does not increase the player count, as it allows 1 player to hold an exploding kitten in their hand.

---

Currently this mod produces an index exception with 6 players, even if imploding kittens is added.

**Comment by andrsdt** [comment]
The index exception was being produced because in some cases (when there were 6 players and 6 defuses), the defuse deck was empty and trying to summon a button attached to the deck produced an exception. The button has now been attached to an independent entity and the support for up to 9 players is the following:

If there are 6 players, you have to either play with Imploding Kittens or with the NSFW deck merged of the default one. In case you didn't select any, the NSFW deck will be added automatically.

If there are between 6 and 9 players, you have to choose , at least, the NSFW deck. Expansions can also be selected.

I'm closing the issue now, let me know if any new bugs appear. Thanks!
